"""add source fields to test_runs

Revision ID: cfccb0468471
Revises: b9c5fe26f234
Create Date: 2026-04-19 09:23:45.085001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfccb0468471'
down_revision: Union[str, Sequence[str], None] = 'b9c5fe26f234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_runs', sa.Column('source_name', sa.String(length=100), nullable=True))
    op.add_column('test_runs', sa.Column('external_run_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_runs', 'external_run_id')
    op.drop_column('test_runs', 'source_name')
    # ### end Alembic commands ###
